{
	"data": "ENC[AES256_GCM,data:hhYSzcNvkmKd8ZEXMOeipc5eHLdyY1k5pmVs7bTqIouS+h0VQtorEj5rwPjY+NKrkzEyjzY3vufn93p7eg494HvVc8bUIcl7DXYZOYNnJ7/WeJ6GAbP6+UMRdVOJl8oVCWevNY+IVOx+twBTVyZKoLnx2yi1z2tPu0phR9JaC3zpRZCarfXdaatmJ5ARQoQ9lzLup5ohDCoPSaaiYjYRY4lBNCsbJhc6oNN0I9itF6s2MK9Z7NVyV4tbkwUjwf58oRUGb/jJ2trJcsQ=,iv:8SkXUnui7kXbRt0/OJPK2ix/+NtjXtKSgcs9a/1d7Go=,tag:F6xhcpGR5ygci/9SpR2EHg==,type:str]",
	"sops": {
		"age": [
			{
				"recipient": "age156k286rx49qdkj7fddj8f7gwd92n6r0wunu7260lxcweszfy3evsc7cdap",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOQWN6SmpvVTJEYk1mWmw4\nb3RWMXppNHBtQlBQdjZNVTNzUEM0YVBEVFg0CkllU1IwcHZKaS9pSkFhNGdjSWZW\nRWVjL0d5TDMrNUJYVm0zYVN6aEhLZG8KLS0tIE5JYnJzb3lZV1pLN21EeUVxSjR5\nZUU4V24vUitzYmM3VnZuWjRlQ2doZEkKIpo3m4RzijOjBsivcyVhg+tA6FGUQCt7\nfkVNHbeoFRNp21Ry7skwNeLSg5/Veht8ZxIR5w9QAehm8c9WkKzxDg==\n-----END AGE ENCRYPTED FILE-----\n"
			},
			{
				"recipient": "age19w4ecgrxgnelsdcnn26xfu8mkgrypmuxmgftccu5gt6ug64w3qfqvqdmpz",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHYUJtRHlWUm5TMkUwWTkw\nbkF3aU9uYVQ3cGxQY1Z0VWkzeGZmbUtSNGh3CjdGRHZxbG4zZ0cyd2NkNHg5U080\nWUJPZnlseHNmYjhhcCtoaFJtRE1ua1UKLS0tIGtJazlRZ29NeU1lVVdOMmdxd0kr\nTGZnRmJOdjAvbDM1SmhJdUVpemFMWnMKleSp9+CYGR2ztJ+aQBeKz4SpBfP1CT8D\nr+kPr/HJnDMvVMDutOn8Gjso5d/KbgCEhX+2HGfhFzpPDk/TOfJ5ww==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2026-04-29T13:42:15Z",
		"mac": "ENC[AES256_GCM,data:DPceQAQ9yLvofsoRFWPMbMswU8Lm9AkJZreJdK9lXdQgFGNSLoGMiYbwcvsueZ+rggeaDoEfN0U+UM3Y8aKSJ72oP3e3xLloF97IltJ9kZUYZ9V36omuFCLWE8jPfydi2VikuoVdB6TSc/9Dla5CFOAnNtC3hvASQXlpbt6QmgQ=,iv:+HD+WkSakpNdkNQXkBpjgaRMN7pngkeIfSwpcTtH1To=,tag:0QkFiHjT2elkYbujziiBrg==,type:str]",
		"version": "3.12.2"
	}
}
