{
	"data": "ENC[AES256_GCM,data:h4tZGB0BgbcHSvyYMYnQhM07Xg6iWjRiokkzJ/ZCP38NKc/d7rGtZQpO2HjF1zGFmI6WNk0LeT7NEh9UxdYXlQNiqfMCKVilPukIM7N/jPhT0BbNJ5wHkyrosrBEOGrzzskPu3WAMagQJ0s7gTTePo8zZ+TosA98z2SFFebCtrh+HfUtlOG4m/F3qqkSPWcul4PIHI7fMdhKuBy+PlkxsMVGAR0LtoNprCap0ubrbMkaxk4m0aOjbDfacIrYvw4Sz8TCqeA+TyRZ8ukH5IkRz9T59DsSgLCL/sUyBAVMBCrw8Cu149QQuNj38gymNdXy528gsrhq9Q==,iv:HJ/9lZZAPb7eX12TpcjcRkNx1zmZkNXmVjEGHQiDrGw=,tag:Y8LxVIH9tL2ydHk2TnQnFA==,type:str]",
	"sops": {
		"age": [
			{
				"recipient": "age156k286rx49qdkj7fddj8f7gwd92n6r0wunu7260lxcweszfy3evsc7cdap",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEWGhHVXVFV3ZPbW5IUm5x\ncWJneFYyeU1zUFk2OWwySk5LWlNFbUxpWm1VCjQyVDRRODlySm5LeVpnZFVZZkpE\naEZGSjZtQStXUGIxdEsrdzZTVTl1YWcKLS0tIGZwNG1sOHhEQ21YZFBWL1lMcFNh\ncVAwekJNZ1RyWXZLeDhaU0xGbENyT3MKedlw8bicvnWSJnF8OeK55AVMEoogQ4Vq\nGgqez0Yo2cQqxwStkc0TUhMQKkV9Ip7ZDd4oVaWvfGvNl9dcEDTs6A==\n-----END AGE ENCRYPTED FILE-----\n"
			},
			{
				"recipient": "age19w4ecgrxgnelsdcnn26xfu8mkgrypmuxmgftccu5gt6ug64w3qfqvqdmpz",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBUEhXOUd1anJuRzIrNGVN\nMnRIcldzTERwM3ZMcXJPQW1kQ3RLeFloY0g0Ck40L0s2TEJ0S1ZQM2Y0L2w1NTU3\nM1JrVFNHaGFVSnVBN0pySko5ck8zYXMKLS0tIHJWTVNtd1VTTUVYVU9ybGF1eXI0\nZlE0eE50dy9LZHE3VEN6ZWRuMklPWGcKysn92oiJsPxMP4TTtksxJM3Fk76u90iw\n0kUOmQkU8q7qw63gkAKqw6ME5IUbMndNRgCaXtICoNOsLVmWG5uGrA==\n-----END AGE ENCRYPTED FILE-----\n"
			},
			{
				"recipient": "age10gh2knkk4rjhqhsfxt7y559h8uq8lkuegr2gq59jckqvet29mspqe6904g",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxc0RjMnp3MWJkK0MyNkU0\nRlE3ZmdQLzNZOWdLVWtWTmhyMUxWNzYvdlYwCkVoRGhMNWIxbUpJOUxZVjlWenZ6\nZjV6R1JZZUJCVzk3MUJqVlBnUzloNW8KLS0tIEErRVZKY0VEMG03WDlMdVBlOStK\naXkzZ3EvaklVWlV1M3dJcVAzN215T1UK3IxWW8B3C5j71tS5SlWWgFG19dkoH/0j\neJbRCvVvaa3DGZjUGtOHSS3aYnWxiGR1RDolyOyGGbf3XptWricqAg==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2026-05-06T10:01:14Z",
		"mac": "ENC[AES256_GCM,data:lxuCrr9J1xniO63goUzo+PajCJ+hYvBeJCNEp5z6gKb6ATAEWKTmRI6/wXhuZuRiqn5lC09qALymvc/jEcLfUayKlnH29Jaflyqd8xqnM549Nbw1ho9W9fTTuZ9uh4MXJdXeWQYXO8OT2mIP2jA8zsVx/8UxkGSavK0Ur24K6Hk=,iv:nXyT4WBbVl3zpWVpNXkfnK5/m2Rmwt9HX/3gi4LgBKw=,tag:YnR+0S2XtF9qe0tpdv8hGQ==,type:str]",
		"version": "3.12.2"
	}
}
